Fix of bug 1396686
Root Cause:
_() was removed from DEBUG level logging

Fix:
Use "unicode" directly according to the error message:
UnicodeError: Message objects do not support str() because they may contain non-ascii characters. Please use unicode() or translate() instead.